# Generated by Django 2.1.4 on 2019-01-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_info',
            name='data',
            field=models.CharField(max_length=1000),
        ),
    ]
