# Generated by Django 2.1.4 on 2019-01-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidu', '0002_auto_20190103_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address_info',
            options={'verbose_name': '地图模型', 'verbose_name_plural': '地图模型'},
        ),
        migrations.RemoveField(
            model_name='address_info',
            name='data',
        ),
        migrations.AddField(
            model_name='address_info',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='address_info',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='address_info',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='address_info',
            name='latitude',
            field=models.FloatField(verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='address_info',
            name='longitude',
            field=models.FloatField(verbose_name='经度'),
        ),
    ]
