# Generated by Django 2.1.4 on 2019-01-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidu', '0003_auto_20190103_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_info',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='视频地址'),
        ),
    ]
