# Generated by Django 2.1.4 on 2019-01-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidu', '0004_address_info_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('number', models.IntegerField(verbose_name='站点编号')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='电话')),
                ('desc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='介绍')),
                ('video', models.URLField(blank=True, null=True, verbose_name='视频地址')),
            ],
            options={
                'verbose_name': '地图模型',
                'verbose_name_plural': '地图模型',
            },
        ),
    ]
